import {useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {ArrowDown,ArrowUpRight,Check,Clipboard,Code2,Download,ExternalLink, Github, Instagram, Mail, Menu, Monitor, Moon, Phone, Sparkles, Terminal, X, Zap} from 'lucide-react';
import ParticleField from './components/ParticleField';
import CustomCursor from './components/CustomCursor';
import ScrollProgress from './components/ScrollProgress';
import MagneticButton from './components/MagneticButton';
import {portfolio} from './data/portfolio';
import useScrollReveal from './hooks/useScrollReveal';

const ease=[.22,1,.36,1];
function Reveal({children,className=''}){const [ref,show]=useScrollReveal();return <motion.div ref={ref} className={className} initial={{opacity:0,y:28}} animate={show?{opacity:1,y:0}:{}} transition={{duration:.7,ease}}>{children}</motion.div>}
function Tilt({children,className=''}){const [t,setT]=useState('');return <div className={`tilt ${className}`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();const rx=((e.clientY-r.top)/r.height-.5)*-9,ry=((e.clientX-r.left)/r.width-.5)*9;setT(`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) scale(1.015)`)}} onPointerLeave={()=>setT('')} style={{transform:t}}>{children}</div>}
function App(){const reduce=useReducedMotion();const [menu,setMenu]=useState(false),[active,setActive]=useState('home'),[copied,setCopied]=useState(''),[back,setBack]=useState(false),[index,setIndex]=useState(0);const [mouse,setMouse]=useState({x:.5,y:.5});
useEffect(()=>{const on=()=>{const ids=['home','about','skills','projects','contact'];let cur='home';for(const id of ids){const el=document.getElementById(id);if(el&&scrollY>=el.offsetTop-180)cur=id}setActive(cur);setBack(scrollY>700)};addEventListener('scroll',on,{passive:true});on();return()=>removeEventListener('scroll',on)},[]);
useEffect(()=>{const f=e=>setMouse({x:e.clientX/innerWidth,y:e.clientY/innerHeight});addEventListener('pointermove',f,{passive:true});return()=>removeEventListener('pointermove',f)},[]);
useEffect(()=>{if(reduce)return;const id=setInterval(()=>setIndex(i=>(i+1)%portfolio.titles.length),2400);return()=>clearInterval(id)},[reduce]);
const copy=async(type,value)=>{await navigator.clipboard?.writeText(value);setCopied(type);setTimeout(()=>setCopied(''),1800)};
const nav=['home','about','skills','projects','contact'];
return <div className="min-h-screen text-zinc-100 selection:bg-cyan-300/30">
<ScrollProgress/><ParticleField/><CustomCursor/>
<div className="fixed inset-0 z-0 grid-bg opacity-70"/><div className="fixed -left-40 top-40 w-96 h-96 rounded-full bg-cyan-500/20 orb"/><div className="fixed -right-40 top-[55%] w-[28rem] h-[28rem] rounded-full bg-purple-600/20 orb"/>
<nav className="fixed top-0 left-0 right-0 z-50 px-4 sm:px-8 py-4"><div className="mx-auto max-w-6xl glass rounded-2xl px-4 sm:px-5 h-14 flex items-center justify-between"><a href="#home" className="font-black tracking-tight text-lg"><span className="text-cyan-300">M</span>M<span className="text-purple-400">.</span></a><div className="hidden md:flex items-center gap-1">{nav.map(n=><a key={n} href={`#${n}`} className={`px-3 py-2 rounded-lg text-xs uppercase tracking-[.18em] transition ${active===n?'text-cyan-300 bg-cyan-300/10':'text-zinc-400 hover:text-white'}`}>{n}</a>)}</div><a href="#contact" className="hidden sm:inline-flex rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-xs font-semibold text-cyan-200 hover:bg-cyan-300/20">Let's talk <ArrowUpRight size={14}/></a><button className="md:hidden p-2" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="md:hidden mx-auto mt-2 max-w-6xl glass rounded-2xl p-3">{nav.map(n=><a onClick={()=>setMenu(false)} key={n} href={`#${n}`} className="block rounded-xl px-4 py-3 uppercase text-xs tracking-widest text-zinc-300 hover:bg-white/5">{n}</a>)}</div>}</nav>
<main className="relative z-10">
<section id="home" className="min-h-screen flex items-center px-5 pt-24"><div className="mx-auto max-w-6xl w-full grid lg:grid-cols-[1.2fr_.8fr] gap-12 items-center"><div style={{textShadow:`${(mouse.x-.5)*14}px ${(mouse.y-.5)*14}px 28px rgba(34,211,238,.14)`}}><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.1}} className="inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/5 px-3 py-1.5 text-xs text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/> Available for work</motion.div><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.2}} className="mt-8 text-sm uppercase tracking-[.28em] text-zinc-500">Hello, world — I'm</motion.p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.3,duration:.8,ease}} className="mt-3 text-5xl sm:text-7xl lg:text-8xl font-black tracking-[-.06em] leading-[.9]">Mohsin Islam<br/><span className="gradient-text">Mahim.</span></motion.h1><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.6}} className="mt-7 flex items-center gap-3 text-xl sm:text-2xl text-zinc-300">I build as a <span className="gradient-text font-bold min-w-[190px]">{portfolio.titles[index]}</span><span className="animate-pulse text-cyan-300">_</span></motion.div><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.7}} className="mt-6 max-w-xl text-zinc-400 leading-7">Digital experiences with sharp interfaces, thoughtful motion and a little bit of neon chaos. I turn ideas into things people actually want to use.</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.8}} className="mt-8 flex flex-wrap gap-3"><MagneticButton href="/Mohsin-Islam-Mahim-Resume.txt" download className="gap-2 bg-white text-zinc-950 px-6 py-3.5 font-bold">Download Resume <Download size={17}/></MagneticButton><MagneticButton href="#projects" className="gap-2 border border-white/10 bg-white/5 px-6 py-3.5 text-white">Explore work <ArrowDown size={17}/></MagneticButton></motion.div></div><div className="hidden lg:block"><div className="relative aspect-square max-w-md ml-auto"><div className="absolute inset-8 rounded-[3rem] border border-cyan-300/20 rotate-6"/><div className="absolute inset-12 rounded-[3rem] border border-purple-400/20 -rotate-6"/><Tilt className="absolute inset-16"><div className="glass glow rounded-[2.5rem] h-full flex items-center justify-center overflow-hidden"><div className="absolute w-44 h-44 bg-cyan-400/20 rounded-full blur-3xl"/><div className="relative text-center"><Terminal className="mx-auto text-cyan-300" size={42}/><div className="mt-5 text-5xl font-black tracking-tighter">&lt;/&gt;</div><div className="mt-2 text-xs uppercase tracking-[.3em] text-zinc-500">build • ship • repeat</div></div></div></Tilt></div></div></div></section>
<section id="about" className="px-5 py-28"><div className="mx-auto max-w-6xl"><Reveal><div className="flex items-end justify-between gap-5 mb-10"><div><p className="text-cyan-300 text-xs uppercase tracking-[.25em]">01 / About</p><h2 className="mt-3 text-4xl sm:text-5xl font-black tracking-tight">Crafting digital <span className="gradient-text">energy.</span></h2></div><Sparkles className="hidden sm:block text-purple-400"/></div></Reveal><div className="grid md:grid-cols-3 gap-4"><Reveal className="md:col-span-2"><Tilt className="h-full"><div className="glass rounded-3xl p-7 sm:p-9 h-full"><p className="text-xl sm:text-2xl leading-relaxed text-zinc-200">I'm a creator and developer who loves turning a blank screen into an experience that feels <span className="text-cyan-300">alive.</span></p><p className="mt-5 text-zinc-400 leading-7">From responsive frontends to animated interactions, I care about the details that make a product feel premium. My toolkit is a mix of modern web technologies, design instincts and relentless curiosity.</p></div></Tilt></Reveal><Reveal><Tilt className="h-full"><div className="glass rounded-3xl p-7 h-full flex flex-col justify-between"><Code2 className="text-purple-400" size={32}/><div><div className="text-4xl font-black">24/7</div><p className="text-zinc-500 mt-1">curiosity mode</p></div></div></Tilt></Reveal></div></div></section>
<section id="skills" className="px-5 py-28"><div className="mx-auto max-w-6xl"><Reveal><p className="text-cyan-300 text-xs uppercase tracking-[.25em]">02 / Skills</p><h2 className="mt-3 text-4xl sm:text-5xl font-black">My <span className="gradient-text">stack.</span></h2></Reveal><div className="mt-10 grid md:grid-cols-2 gap-4">{portfolio.skills.map(([name,val],i)=><Reveal key={name}><div className="glass rounded-3xl p-6 hover:neon transition"><div className="flex justify-between mb-3"><span className="font-semibold">{name}</span><span className="text-cyan-300 text-sm">{val}%</span></div><div className="skill-bar"><motion.div initial={{width:0}} whileInView={{width:`${val}%`}} viewport={{once:true}} transition={{duration:1,delay:i*.1,ease}} className="skill-fill"/></div></div></Reveal>)}</div></div></section>
<section id="projects" className="px-5 py-28"><div className="mx-auto max-w-6xl"><Reveal><div className="flex items-end justify-between"><div><p className="text-cyan-300 text-xs uppercase tracking-[.25em]">03 / Selected work</p><h2 className="mt-3 text-4xl sm:text-5xl font-black">Built to <span className="gradient-text">stand out.</span></h2></div><Monitor className="hidden sm:block text-cyan-300"/></div></Reveal><div className="mt-10 grid lg:grid-cols-3 gap-5">{portfolio.projects.map((p,i)=><Reveal key={p.title}><Tilt className="h-full"><article className="glass rounded-3xl p-6 h-full group hover:neon transition"><div className="h-44 rounded-2xl bg-gradient-to-br from-cyan-400/10 via-zinc-900 to-purple-500/10 border border-white/5 flex items-center justify-center overflow-hidden"><div className="text-6xl font-black text-white/10 group-hover:text-cyan-300/20 transition">0{i+1}</div></div><p className="mt-5 text-xs uppercase tracking-[.2em] text-purple-300">{p.tag}</p><h3 className="mt-2 text-2xl font-bold">{p.title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{p.desc}</p><div className="mt-5 flex flex-wrap gap-2">{p.tech.map(t=><span key={t} className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-zinc-400">{t}</span>)}</div><div className="mt-6 flex items-center gap-2 text-sm text-cyan-300">View concept <ArrowUpRight size={15}/></div></article></Tilt></Reveal>)}</div></div></section>
<section id="contact" className="px-5 pt-28 pb-16"><div className="mx-auto max-w-6xl"><Reveal><div className="text-center"><p className="text-cyan-300 text-xs uppercase tracking-[.25em]">04 / Contact</p><h2 className="mt-4 text-5xl sm:text-7xl font-black tracking-[-.05em]">Let's make something<br/><span className="gradient-text">ridiculous.</span></h2><p className="mx-auto mt-6 max-w-lg text-zinc-500">Have an idea, a project, or just want to say hi? My inbox is open.</p></div></Reveal><div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[[Mail,'Email',portfolio.email,'mailto:'+portfolio.email,'hover:border-red-400/40 hover:text-red-300'],[Phone,'Phone',portfolio.phone,'tel:'+portfolio.phone,'hover:border-emerald-400/40 hover:text-emerald-300'],[Github,'GitHub','freakmahim67',portfolio.github,'hover:border-white/40 hover:text-white'],[Instagram,'Instagram','@esdeemhm',portfolio.instagram,'hover:border-pink-400/40 hover:text-pink-300']].map(([Icon,label,value,href,color])=><Tilt key={label}><a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer" className={`glass rounded-3xl p-6 block transition ${color}`}><Icon size={24}/><div className="mt-8 text-xs uppercase tracking-[.2em] text-zinc-500">{label}</div><div className="mt-1 font-semibold truncate">{value}</div></a></Tilt>)}</div><div className="mt-5 glass rounded-3xl p-4 flex flex-wrap gap-3 justify-center"><button onClick={()=>copy('email',portfolio.email)} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm flex items-center gap-2 hover:bg-white/10">{copied==='email'?<Check size={15}/>:<Clipboard size={15}/>} Copy email</button><button onClick={()=>copy('phone',portfolio.phone)} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm flex items-center gap-2 hover:bg-white/10">{copied==='phone'?<Check size={15}/>:<Clipboard size={15}/>} Copy phone</button></div></div></section>
<footer className="relative z-10 px-5 pb-8"><div className="mx-auto max-w-6xl border-t border-white/10 pt-6 flex flex-col sm:flex-row justify-between gap-3 text-xs text-zinc-600"><span>© {new Date().getFullYear()} Mohsin Islam Mahim</span><span>Designed with curiosity • built with code</span></div></footer>
</main>{back&&<button onClick={()=>scrollTo({top:0,behavior:'smooth'})} className="fixed bottom-6 right-6 z-50 p-3 rounded-full glass neon text-cyan-300 hover:scale-110 transition"><ArrowUp size={18}/></button>}
<AnimatePresence>{copied&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}} className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[80] glass rounded-full px-5 py-3 text-sm flex items-center gap-2"><Check size={16} className="text-emerald-300"/> {copied==='email'?'Email':'Phone'} copied</motion.div>}</AnimatePresence>
</div>}
export default App
